### ISSUE TITLE
Problems with cm13/toybox

### ISSUE THREAD

**Issue by Spleeeno** [SimonMarquis/Android-PreferencesManager#13]
Since cm replaced busybox with toybox, if you try to start the app with cm13, you just get the "Problem detected" error msg, but there's no way to change the path to busybox in the settings.

oandbackup has such a path-setting, so its rather easy to just change it to /system/bin/toybox and everything is back to normal.

Is there any chance to get such a setting for Preferences Manager?

Many thanks in advance!

**Comment by SimonMarquis** [comment]
It does work fine on my build of cm 13.
Please verify the root access through Privacy Guard, and copy the logcat when trying to access this app.
Root binaries should always be available in /system/bin or /system/xbin (via symbolic link)

**Comment by perkabalo** [comment]
Logcat: http://hastebin.com/ecovuhusic.avrasm

Verified root access, are you possibly running a custom kernel with your cm-13.0 build, maybe it has busybox integrated?

**Comment by SimonMarquis** [comment]
I don't think so. I used the original build from Cyanogen.

**Comment by SimonMarquis** [comment]
New release 1.8.2 available.
All commands are issued with libsuperuser.
Re-open if it still doesn't work.
