### ISSUE TITLE
empty data from preference-files with whitespaces

### ISSUE THREAD

**Issue by mars3142** [SimonMarquis/Android-PreferencesManager#15]
If the preference file name includes a whitespace (e.g. space) I can't edit the preferences. The Android framework does it perfect.

**Comment by SimonMarquis** [comment]
Does the file fail to load, or does it fail to udpate?

**Comment by SimonMarquis** [comment]
A quick fix would be to add quotes around filenames when executing shell commands.

**Comment by mars3142** [comment]
The Preference Manager shows the "empty view", as if the preference doesn't has any items.

**Comment by SimonMarquis** [comment]
[Here ](https://github.com/SimonMarquis/Android-PreferencesManager/blob/7210c43fc4d70467941645b310ac02abbd0f2de0/PreferencesManager/src/main/java/fr/simon/marquis/preferencesmanager/util/Utils.java#L57) might be the issues. I'll try to fix this today.

**Comment by SimonMarquis** [comment]
Do you have an example of app using preference files with spaces?

**Comment by mars3142** [comment]
Sorry no, because I find it while developing my own app (not Open Source). And because the Android framework handled it perfect, I reported it as issue for your app.

**Comment by SimonMarquis** [comment]
Apk pushed to the Google Play Store as version 1.8.3.
