### ISSUE TITLE
Scrollable xml selector is hard to use

### ISSUE THREAD

**Issue by CODeRUS** [SimonMarquis/Android-PreferencesManager#16]
Please think about using simple list view for displaying available xml. If application have >5 xml prefs, it's very hard to find the right one. There are no any sorting, xmls are dispayed in random order.

**Comment by SimonMarquis** [comment]
Hi, unfortunately this project is no longer actively maintained.
Furthermore, I think having a list for xml files will be redundant with the list of preferences...
But you're right, swiping between multiple files can be a bit cumbersome.

**Comment by CODeRUS** [comment]
what about update with alphabetical sorting files then?

**Comment by CODeRUS** [comment]
also an option to copy value to clipboard would be useful also :D

**Comment by SimonMarquis** [comment]
https://github.com/SimonMarquis/Android-PreferencesManager/blob/5c955abddce38e103eddaa2223721459023b8d4f/PreferencesManager/src/main/java/fr/simon/marquis/preferencesmanager/util/Utils.java#L57

I think they already are. But it relies on the full file path into account (path + filename)...

**Comment by SimonMarquis** [comment]
Copying a value to the clipboard is the framework responsibility. Long-pressing in an input field should bring up the copy/paste tooltip.

**Comment by CODeRUS** [comment]
if you want a proof video of sorting issue i can send
