### ISSUE TITLE
Probable Memory Leak

### ISSUE THREAD

**Issue by Robigus92** [SimonMarquis/Android-PreferencesManager#17]
After a double background-foreground event of the AppListActivity there are in heap memory 2 instances more of:

class fr.simon.marquis.preferencesmanager.roboto.RobotoTextView @ 0x12cd9000
class fr.simon.marquis.preferencesmanager.ui.AppAdapter$HeaderViewHolder @ 0x12e20580
class fr.simon.marquis.preferencesmanager.ui.AppAdapter$ViewHolder @ 0x12e20640

It should not be like this because the background-foreground events return to the same GUI state and the memory should stay in the same state as well. It could be a symptom of a bad management of the onStart-onStop lifecycle. 

I have encountered this problem on an Android emulator running 7.1.1 os version.

**Comment by SimonMarquis** [comment]
I don't see any issue here. ViewHolders are retained since Activity doesn't seem to be destroyed in the usecase you're describing.
Are these objects retained after you quit the app with the back button?

**Comment by Robigus92** [comment]
I have developed an automated Memory Leak detection tool which test Activities executing different lifecycle events (rotations, background-foreground, dialog pop-up events) then forcing an ending Garbage Collection. 

The idea is that if the activity lifecycles are well managed there should not be an increase of the used heap memory. 

In AppListActivity, forcing the BF (Background-Foreground) events, it seems to be an increasing trend of those TextView. It means that BF events cause an increase of TextView objects in heap memory. 

The designed Background-Foreground event works switching from an activity to another, involving the Activity's onStart-onStop lifecycle.

**Comment by SimonMarquis** [comment]
https://github.com/SimonMarquis/Android-PreferencesManager/blob/5c955abddce38e103eddaa2223721459023b8d4f/PreferencesManager/src/main/java/fr/simon/marquis/preferencesmanager/ui/AppListActivity.java#L147

Unfortunately the Adapter is always re-created (instead of updating it's internal data), that's the reason why you see doubled instances of ViewHolders.
But since I don't think the Adapter instance is retained anywhere except in the Activity, it won't be a memory leak.
Maybe you have more details about the retained cycles of these objects?

**Comment by Robigus92** [comment]
Have you considered to use a Loader instead of managing the listView through AsyncTask?
Loaders should manage lifecycles automatically, avoiding such problems. 

https://developer.android.com/guide/components/loaders.html

**Comment by SimonMarquis** [comment]
Unfortunately this project is no longer maintained and I don't have enough time to invest in this right now.
